In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing

In [18]:
df = pd.read_csv('../data/residence.csv',sep=";", index_col=False)
df

house_type  house_zip_code  house_rooms  house_square_meters  \
0          Rækkehus            5856            4                102.0   
1             Villa            4760            3                 83.0   
2             Villa            5610            4                103.0   
3             Villa            4440            5                 86.0   
4             Villa            9700            1                 50.0   
...             ...             ...          ...                  ...   
7085  Ejerlejlighed            8000            3                 96.0   
7086          Villa            2610            5                173.0   
7087          Villa            3550            4                186.0   
7088  Ejerlejlighed            2300            3                 91.0   
7089          Villa            6700            8                229.0   

      house_year  house_price  
0           1986      1295000  
1           1954      1295000  
2           1900      1295000  
3           1897       500000  
4           1920       525000  
...          ...          ...  
7085        1969      3699000  
7086        1939      9500000  
7087        1972      3745000  
7088        2010      3750000  
7089        1907      3798000  

[7090 rows x 6 columns]

In [19]:
# transform the data and specify prediction parameters

# Encode the house type from string to integer
label_enc =preprocessing.LabelEncoder()
df['house_type'] = label_enc.fit_transform(df['house_type'].astype(str))

# Set zip for more precise predictions 
#df = df.loc[df['house_zip_code'] == 3480]

# Set type for more precise predictions
df = df.loc[df['house_type'] == 1]

#Data
df_x = df[['house_type','house_zip_code', 'house_rooms', 'house_square_meters',
       'house_year']]
#Target
df_y = df[['house_price']]

#df_y
df_x
#df

house_type  house_zip_code  house_rooms  house_square_meters  house_year
0              1            5856            4                102.0        1986
15             1            6670            4                101.0        1980
22             1            9490            3                 89.0        1983
29             1            7500            4                 99.0        1968
31             1            4500            3                 98.0        1949
...          ...             ...          ...                  ...         ...
7004           1            3500            4                137.0        2022
7014           1            2830            5                111.0        1946
7030           1            9000            5                124.0        1956
7034           1            2880            4                 91.0        1949
7077           1            3450            4                108.0        2018

[580 rows x 5 columns]

In [13]:
# initialize the linear model
reg = linear_model.LinearRegression()

In [14]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.33, random_state=42)

In [8]:
#Normalize

# fit scaler on training data
norm = MinMaxScaler().fit(x_train)


# transform training data
x_train_norm = norm.transform(x_train)


# transform testing dataa
x_test_norm = norm.transform(x_test)

print(x_test_norm)


[[0.66666667 0.76240937 0.25       0.18760403 0.96836983]
 [0.66666667 0.61070831 0.4375     0.28667671 0.94038929]
 [0.         0.55493586 0.25       0.21567462 0.94647202]
 ...
 [0.         0.34300056 0.1875     0.16778949 0.94890511]
 [0.66666667 0.95649749 0.1875     0.21567462 0.92457421]
 [0.66666667 0.7157836  0.1875     0.18760403 0.9513382 ]]


In [ ]:
#Standardize
from sklearn.preprocessing import StandardScaler

scale= StandardScaler()
 
# standardization of dependent variables
x_train_std = scale.fit_transform(x_train)
x_test_std = scale.fit_transform(x_test) 
#print(x_train_std)
#print(x_test)
#print(y_train)

In [15]:
reg.fit(x_train, y_train)
#reg.fit(x_train_std, y_train)
#reg.fit(x_train_norm, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
data = [[0., -0.54772256, -0.6757862, 0.26405096]]
testing_df = pd.DataFrame (data, columns = ['house_zip_code','house_rooms', 'house_square_meters', 'house_year'])
testing_df
# result should be 2395000


In [16]:
# predictions
#pred = reg.predict(testing_df)
pred = reg.predict(x_test)
#pred = reg.predict(x_test_std)
#pred = reg.predict(x_test_norm)
print(pred)

[[ 5444786.06251691]
 [ 7427799.12997654]
 [ 6345825.03021931]
 [ 6834868.09842383]
 [14271444.47874896]
 [ 9739016.07288968]]


In [17]:
y_test

house_price
1129      3795000
1292      4095000
2518      3695000
6884      5495000
5083     10495000
4822      4175000

In [ ]:
#Standerdize the end result
y_test_std = scale.fit_transform(y_test)
y_pred_std = scale.fit_transform(pred)
print(np.mean((y_pred_std - y_test_std)**2))